modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/smashingmods/alchemistry/issues"

[[mods]]
modId="alchemistry"
version="${file.jarVersion}"
displayName="Alchemistry"
authors="SmashingMods"
description='''
'''

[[dependencies.alchemistry]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alchemistry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alchemistry]]
    modId="chemlib"
    mandatory=true
    versionRange="[1.18.2-2.0.0,)"
    ordering="NONE"
    side="BOTH"